import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "./redux/provider";
import Navbar from "./components/Navbar";
import EditPost from "./components/EditPost";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Social media",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
